version: 2

defaults: &defaults
  working_directory: ~/auto-example
  docker:
    - image: circleci/golang:1.12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: make

  release:
    <<: *defaults
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: >
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v9.21.0/auto-linux.gz | gunzip > ~/auto;
          chmod a+x ~/auto;
          auto shipit;

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

      - release:
          requires:
            - build
          filters:
            branches:
              only: master